"""avai.dashboard — package facade.

Re-exports the public surface (app, query functions, CLI) unchanged
after the package split so callers and tests need no edits.
"""
from __future__ import annotations

from avai.host_monitor import Base  # re-export for callers

from .queries import (
    AUTH_SUBSYSTEM_OPTIONS,
    COLLECTOR_MODELS,
    DEFAULT_DB_PATH,
    DEFAULT_PER_PAGE,
    DISPLAY_FIELDS,
    PER_PAGE_OPTIONS,
    SEVERITY_ORDER,
    VERDICTS,
    _AUTH_AGG_WINDOW_HOURS,
    _AUTH_SUBSYSTEM_LABELS,
    _AUTH_VERDICT_SEV,
    _FAMILY_LABEL,
    _FLOW_SEV,
    _HIDDEN_SOURCE_FIELDS,
    _PROTO_BY_SOCK,
    _QUERY_LOG_PATH,
    _SCHEMA_TTL,
    _SCOPE_SEV,
    _SEVERITY_CASE,
    _SORT_FIELDS,
    _STREAMING_COLLECTORS,
    _VULN_SOURCES,
    _addr_scope,
    _attach_ip_enrichment,
    _cache_key,
    _cmdline_str,
    _collector_rows_with_verdict,
    _columns_cache,
    _dns_resolution_level,
    _engine,
    _engine_cache,
    _engine_cache_lock,
    _existing_columns,
    _existing_tables,
    _geo_from_details,
    _geo_richness,
    _host_from_details,
    _log_query,
    _paginate,
    _parse_json_list,
    _parse_json_obj,
    _port_sort_key,
    _query_log_lock,
    _row_and_artifact,
    _session,
    _tables_cache,
    auth_events_aggregated,
    category_options,
    collector_errors,
    collector_options,
    cost_since,
    dns_queries,
    findings,
    judged_since,
    latest_narrative,
    latest_risk,
    latest_run,
    listening_ports,
    network_flows,
    new_alerts,
    persistence_tampering,
    recent_runs,
    risk_trend,
    row_counts,
    runs_total,
    system_integrity,
    verdict_counts,
    verdict_timeseries,
    vulnerabilities,
)
from .app import (
    _LIST_ITEM_RE,
    _MD_TAGS,
    _PKG_DIR,
    _datetime_fmt,
    _ensure_list_blank_lines,
    _flag_emoji,
    _human_bytes,
    _int_arg,
    _pretty_json,
    _prior_run,
    _relative_time,
    _sparkline_points,
    api_chart_verdicts,
    api_notifications_new,
    app,
    fragment_auth_events,
    fragment_collection,
    fragment_dns_queries,
    fragment_errors,
    fragment_findings,
    fragment_header_meta,
    fragment_incident,
    fragment_listening_ports,
    fragment_network,
    fragment_network_flows,
    fragment_overview,
    fragment_persistence,
    fragment_posture,
    fragment_risk,
    fragment_row_counts,
    fragment_runs,
    fragment_sysint,
    fragment_verdicts,
    fragment_vulnerabilities,
    index,
    render_markdown,
)
from .serve import (
    _build_parser,
    _ensure_db_exists,
    _open_browser,
    _serve,
    main,
)


__all__ = [
    "AUTH_SUBSYSTEM_OPTIONS", "Base", "COLLECTOR_MODELS", "DEFAULT_DB_PATH",
    "DEFAULT_PER_PAGE", "DISPLAY_FIELDS", "PER_PAGE_OPTIONS", "SEVERITY_ORDER",
    "VERDICTS", "_AUTH_AGG_WINDOW_HOURS", "_AUTH_SUBSYSTEM_LABELS", "_AUTH_VERDICT_SEV",
    "_FAMILY_LABEL", "_FLOW_SEV", "_HIDDEN_SOURCE_FIELDS", "_LIST_ITEM_RE",
    "_MD_TAGS", "_PKG_DIR", "_PROTO_BY_SOCK", "_QUERY_LOG_PATH",
    "_SCHEMA_TTL", "_SCOPE_SEV", "_SEVERITY_CASE", "_SORT_FIELDS",
    "_STREAMING_COLLECTORS", "_VULN_SOURCES", "_addr_scope", "_attach_ip_enrichment",
    "_build_parser", "_cache_key", "_cmdline_str", "_collector_rows_with_verdict",
    "_columns_cache", "_datetime_fmt", "_dns_resolution_level", "_engine",
    "_engine_cache", "_engine_cache_lock", "_ensure_db_exists", "_ensure_list_blank_lines",
    "_existing_columns", "_existing_tables", "_flag_emoji", "_geo_from_details",
    "_geo_richness", "_host_from_details", "_human_bytes", "_int_arg",
    "_log_query", "_open_browser", "_paginate", "_parse_json_list",
    "_parse_json_obj", "_port_sort_key", "_pretty_json", "_prior_run",
    "_query_log_lock", "_relative_time", "_row_and_artifact", "_serve",
    "_session", "_sparkline_points", "_tables_cache", "api_chart_verdicts",
    "api_notifications_new", "app", "auth_events_aggregated", "category_options",
    "collector_errors", "collector_options", "cost_since", "dns_queries",
    "findings", "fragment_auth_events", "fragment_collection", "fragment_dns_queries",
    "fragment_errors", "fragment_findings", "fragment_header_meta", "fragment_incident",
    "fragment_listening_ports", "fragment_network", "fragment_network_flows", "fragment_overview",
    "fragment_persistence", "fragment_posture", "fragment_risk", "fragment_row_counts",
    "fragment_runs", "fragment_sysint", "fragment_verdicts", "fragment_vulnerabilities",
    "index", "judged_since", "latest_narrative", "latest_risk",
    "latest_run", "listening_ports", "main", "network_flows",
    "new_alerts", "persistence_tampering", "recent_runs", "render_markdown",
    "risk_trend", "row_counts", "runs_total", "system_integrity",
    "verdict_counts", "verdict_timeseries", "vulnerabilities",
]
